-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost:3306
-- Tiempo de generación: 09-03-2021 a las 20:31:45
-- Versión del servidor: 5.7.24
-- Versión de PHP: 7.4.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `pokedex`
--
CREATE DATABASE IF NOT EXISTS `pokedex` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;
USE `pokedex`;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `pokemons`
--

CREATE TABLE `pokemons` (
  `id` bigint(20) NOT NULL,
  `image` text COLLATE utf8_spanish_ci,
  `image_shiny` text COLLATE utf8_spanish_ci,
  `code` varchar(6) COLLATE utf8_spanish_ci DEFAULT NULL,
  `name` varchar(200) COLLATE utf8_spanish_ci NOT NULL,
  `description` varchar(256) COLLATE utf8_spanish_ci DEFAULT NULL,
  `height` double NOT NULL,
  `weight` double NOT NULL,
  `ability` varchar(256) COLLATE utf8_spanish_ci DEFAULT NULL,
  `ability_description` varchar(256) COLLATE utf8_spanish_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

--
-- Volcado de datos para la tabla `pokemons`
--

INSERT INTO `pokemons` (`id`, `image`, `image_shiny`, `code`, `name`, `description`, `height`, `weight`, `ability`, `ability_description`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/1.png', '001', 'Bulbasaur', 'Una Rara Semilla Le Fue Plantada En El Lomo Al Nacer.\nLa Planta Brota Y Crece Con Este Pokémon.', 7, 69, 'Overgrow', 'Potencia Los Ataques De Tipo\nPlanta En Un Apuro.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(2, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/2.png', '002', 'Ivysaur', 'Este Pokémon Tiene Un Bulbo En El Lomo. Dicen Que,\nAl Absorber Nutrientes, El Bulbo Se Transforma En Una\nFlor Grande.', 10, 130, 'Overgrow', 'Potencia Los Ataques De Tipo\nPlanta En Un Apuro.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(3, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/3.png', '003', 'Venusaur', 'Llena Su Cuerpo De Energía Con Los Rayos Solares Que\nCaptan Los Anchos Pétalos De Su Flor.', 20, 1000, 'Overgrow', 'Potencia Los Ataques De Tipo\nPlanta En Un Apuro.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(4, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/4.png', '004', 'Charmander', 'La Llama De Su Cola Indica La Fuerza Vital De\nCharmander. Será Brillante Si Está Sano.', 6, 85, 'Blaze', 'Potencia Los Ataques De Tipo\nFuego En Un Apuro.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(5, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/5.png', '005', 'Charmeleon', 'Suele Usar La Cola Para Derribar A Su Rival. Cuando Lo\nTira, Se Vale De Sus Afiladas Garras Para Acabar Con él.', 11, 190, 'Blaze', 'Potencia Los Ataques De Tipo\nFuego En Un Apuro.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/6.png', '006', 'Charizard', 'Cuando Lanza Una Descarga De Fuego Supercaliente, La\nRoja Llama De Su Cola Brilla Más Intensamente.', 17, 905, 'Blaze', 'Potencia Los Ataques De Tipo\nFuego En Un Apuro.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(7, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/7.png', '007', 'Squirtle', 'Se Protege Con Su Caparazón Y Luego Contraataca\nLanzando Agua A Presión Cuando Tiene Oportunidad.', 5, 90, 'Torrent', 'Potencia Los Ataques De Tipo\nAgua En Un Apuro.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/8.png', '008', 'Wartortle', 'Si Es Golpeado, Esconderá Su Cabeza. Aun Así, Su Cola\nPuede Seguir Golpeando.', 10, 225, 'Torrent', 'Potencia Los Ataques De Tipo\nAgua En Un Apuro.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(9, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/9.png', '009', 'Blastoise', 'Para Acabar Con Su Enemigo, Lo Aplasta Con El Peso De\nSu Cuerpo. En Momentos De Apuro, Se Esconde En El\nCaparazón.', 16, 855, 'Torrent', 'Potencia Los Ataques De Tipo\nAgua En Un Apuro.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(10, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10.png', '010', 'Caterpie', 'Para Protegerse Despide Un Hedor Horrible De Sus\nAntenas, Con El Que Repele A Sus Enemigos.', 3, 29, 'Shield-dust', 'Anula El Efecto Secundario Del\nAtaque Sufrido.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(11, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/11.png', '011', 'Metapod', 'Su Frágil Cuerpo Está Recubierto De Una Coraza Dura\nComo El Acero. Permanece Quieto En Su Desarrollo.', 7, 99, 'Shed-skin', 'Cura Los Problemas De Estado\nMudando La Piel.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(12, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/12.png', '012', 'Butterfree', 'Adora El Néctar De Las Flores. Puede Localizar Hasta Las\nMás Pequeñas Cantidades De Polen.', 11, 320, 'Compound-eyes', 'Aumenta La Precisión Del\nPokémon.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(13, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/13.png', '013', 'Weedle', 'Es Lebt Bevorzugt In Wäldern Und In Hohem Gras.\nAuf Dem Kopf Trägt Es Einen Circa 5 Cm Langen,\nSpitzen, Giftigen Stachel.', 3, 32, 'Shield-dust', 'Anula El Efecto Secundario Del\nAtaque Sufrido.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(14, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/14.png', '014', 'Kakuna', 'Casi Incapaz De Moverse, Este Pokémon Solo Puede\nEndurecer Su Caparazón Para Protegerse.', 6, 100, 'Shed-skin', 'Cura Los Problemas De Estado\nMudando La Piel.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(15, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/15.png', '015', 'Beedrill', 'Tiene 3 Aguijones Venenosos En Sus Patas Y Cola.\nSuelen Pinchar A Sus Enemigos Repetidas Veces.', 10, 295, 'Swarm', 'Potencia Los Ataques De Tipo\nBicho En Un Apuro.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(16, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/16.png', '016', 'Pidgey', 'Muy Común En Bosques Y Selvas. Aletea Al Nivel Del\nSuelo Para Levantar La Gravilla.', 3, 18, 'Keen-eye', 'Evita Que Disminuya La Precisión.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(17, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/17.png', '017', 'Pidgeotto', 'Tiene Unas Garras Desarrolladas. Puede Atrapar Un\nExeggcute Y Transportarlo Desde Una Distancia De\nCasi 100 Km.', 11, 300, 'Keen-eye', 'Evita Que Disminuya La Precisión.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(18, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/18.png', '018', 'Pidgeot', 'Cuando Caza, Vuela Muy Deprisa A Ras Del Agua Y\nSorprende A Inocentes Presas Como Magikarp.', 15, 395, 'Keen-eye', 'Evita Que Disminuya La Precisión.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(19, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/19.png', '019', 'Rattata', 'Vive Allí Donde Haya Comida Disponible. Busca Todo\nEl Día, Sin Descanso, Algo Comestible.', 3, 35, 'Run-away', 'Permite Escapar De Todos Los\nPokémon Salvajes.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(20, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/20.png', '020', 'Raticate', 'Lima Sus Colmillos Royendo Objetos Duros. Con Ellos\nPuede Destruir Incluso Paredes De Hormigón.', 7, 185, 'Run-away', 'Permite Escapar De Todos Los\nPokémon Salvajes.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(21, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/21.png', '021', 'Spearow', 'Es Beschützt Sein Gebiet Stets Vor Eindringlingen.\nDaher Fliegt Es Ständig Wild Umher.', 3, 20, 'Keen-eye', 'Evita Que Disminuya La Precisión.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(22, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/22.png', '022', 'Fearow', 'Con Sus Enormes Y Magníficas Alas, Puede Seguir\nVolando Sin Tener Que Aterrizar Para Descansar.', 12, 380, 'Keen-eye', 'Evita Que Disminuya La Precisión.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(23, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/23.png', '023', 'Ekans', 'Cuanto Más Viejo, Más Crece Este Pokémon. Por La\nNoche, Descansa En Las Ramas De Los árboles.', 20, 69, 'Intimidate', 'Baja El Ataque Del Rival.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(24, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/24.png', '024', 'Arbok', 'El Dibujo Que Tiene En La Panza Aterroriza. Los Rivales\nMás Débiles Salen Huyendo Al Verlo.', 35, 650, 'Intimidate', 'Baja El Ataque Del Rival.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(25, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/25.png', '025', 'Pikachu', 'Es Streckt Seinen Schweif Nach Oben, Um Seine\nUmgebung Zu Prüfen. Häufig Fährt Ein Blitz Hinein.', 4, 60, 'Static', 'Puede Paralizar Al Mínimo\nContacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(26, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/26.png', '026', 'Raichu', 'Cuando Se Carga De Electricidad, Sus Músculos Se\nTensan Y Se Vuelve Más Agresivo De Lo Normal.', 8, 300, 'Static', 'Puede Paralizar Al Mínimo\nContacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(27, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/27.png', '027', 'Sandshrew', 'Este Pokémon Permanece Bajo Tierra. Si Se Siente\nAmenazado, Se Enrosca Para Defenderse.', 6, 120, 'Sand-veil', 'Aumenta La Evasión En Las\nTormentas De Arena.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(28, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/28.png', '028', 'Sandslash', 'Si Cava A Gran Velocidad, Puede Que Se Le Caigan Las\nGarras Y Púas. Vuelven A Crecerle En Un Día.', 10, 295, 'Sand-veil', 'Aumenta La Evasión En Las\nTormentas De Arena.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(29, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/29.png', '029', 'Nidoran-f', 'Aunque Pequeñas, Sus Venenosas Púas Son Muy\nPeligrosas. Tienen Un Cuerno Más Pequeño Que\nLos Machos.', 4, 70, 'Poison-point', 'Puede Envenenar Al Mínimo\nContacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(30, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/30.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/30.png', '030', 'Nidorina', 'Tiene Un Carácter Afable. Emite Ondas Ultrasónicas\nPara Confundir Al Enemigo.', 8, 200, 'Poison-point', 'Puede Envenenar Al Mínimo\nContacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(31, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/31.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/31.png', '031', 'Nidoqueen', 'Usa Su Cuerpo Duro Y Escamoso Para Sellar La Entrada\nA Su Madriguera Y Protegerse De Los Depredadores.', 13, 600, 'Poison-point', 'Puede Envenenar Al Mínimo\nContacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(32, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/32.png', '032', 'Nidoran-m', 'Es Untersucht Die Umgebung, Indem Es Die Ohren\nSpitzt Und Lauscht. Sein Giftiges Horn Schützt Es.', 5, 90, 'Poison-point', 'Puede Envenenar Al Mínimo\nContacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(33, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/33.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/33.png', '033', 'Nidorino', 'Levanta Sus Grandes Orejas Para Vigilar. Si Detecta\nAlgo, Atacará De Inmediato.', 9, 195, 'Poison-point', 'Puede Envenenar Al Mínimo\nContacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(34, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/34.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/34.png', '034', 'Nidoking', 'Es Fácil Reconocerlo Por Tener Una Dura Piel Y Un Gran\nCuerno Lleno De Peligrosísimo Veneno.', 14, 620, 'Poison-point', 'Puede Envenenar Al Mínimo\nContacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/35.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/35.png', '035', 'Clefairy', 'Se Dice Que La Felicidad Llegará A Quien Vea A Un Grupo\nDe Clefairy Bailando A La Luz De La Luna Llena.', 6, 75, 'Cute-charm', 'Tocar Al Pokémon Puede Causar\nEnamoramiento.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(36, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/36.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/36.png', '036', 'Clefable', 'Su Oído Es Tan Agudo Que Puede Oír Una Aguja Caer A\n1 Km. Vive En Montañas Solitarias.', 13, 400, 'Cute-charm', 'Tocar Al Pokémon Puede Causar\nEnamoramiento.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(37, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/37.png', '037', 'Vulpix', 'Cuando Nace Solo Tiene Una Cola, Pero A Medida Que\nCrece, Esta Se Va Dividiendo Desde La Punta.', 6, 99, 'Flash-fire', 'Potencia Movimientos De Tipo\nFuego Si Ha Sufrido Antes Alguno.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(38, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/38.png', '038', 'Ninetales', 'Tiene Nueve Colas Y Un Pelaje De Color Dorado.\nDicen Que Este Pokémon Llega A Vivir 1000 Años.', 11, 199, 'Flash-fire', 'Potencia Movimientos De Tipo\nFuego Si Ha Sufrido Antes Alguno.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(39, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/39.png', '039', 'Jigglypuff', 'Cautiva Con La Mirada A Su Enemigo Y Hace Que Se\nQuede Profundamente Dormido Mientras Entona Una\nDulce Melodía.', 5, 55, 'Cute-charm', 'Tocar Al Pokémon Puede Causar\nEnamoramiento.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(40, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/40.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/40.png', '040', 'Wigglytuff', 'Su Piel Es Tan Suave Que Si Dos De Ellos Se Acurrucan\nJuntos, No Querrán Separarse Nunca.', 10, 120, 'Cute-charm', 'Tocar Al Pokémon Puede Causar\nEnamoramiento.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(41, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/41.png', '041', 'Zubat', 'Aunque Carezca De Ojos, Puede Detectar Obstáculos\nCon Las Ondas Ultrasónicas Que Emite Su Boca.', 8, 75, 'Inner-focus', 'Evita El Retroceso.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(42, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/42.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/42.png', '042', 'Golbat', 'Cuando Ataque, Seguirá Chupando Energía De Su\nVíctima, Aunque Pese Tanto Que Ya No Pueda Volar.', 16, 550, 'Inner-focus', 'Evita El Retroceso.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(43, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/43.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/43.png', '043', 'Oddish', 'Durante El Día, Se Agazapa En El Frío Subsuelo Huyendo\nDel Sol. La Luz De La Luna Le Hace Crecer Mucho.', 5, 54, 'Chlorophyll', 'Sube La Velocidad Cuando Hay\nSol.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(44, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/44.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/44.png', '044', 'Gloom', '¡Huele Bastante Mal! De Todas Formas, Una De Cada\nMil Personas Aprecian Su Fétido Olor.', 8, 86, 'Chlorophyll', 'Sube La Velocidad Cuando Hay\nSol.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(45, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/45.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/45.png', '045', 'Vileplume', 'Cuanto Mayores Son Sus Pétalos, Más Tóxico Es Su\nPolen. Le Pesa La Cabeza Y Le Cuesta Mantenerla\nErguida.', 12, 186, 'Chlorophyll', 'Sube La Velocidad Cuando Hay\nSol.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(46, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/46.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/46.png', '046', 'Paras', 'Lleva En El Lomo Dos Setas Parásitas Llamadas\nTochukaso, Que Crecen Con él.', 3, 54, 'Effect-spore', 'Puede Dormir, Envenenar O\nParalizar Al Contacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(47, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/47.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/47.png', '047', 'Parasect', 'Parasect Está Dominado Por Una Seta Parásita Mayor\nQue él. Dispersa Esporas Venenosas.', 10, 295, 'Effect-spore', 'Puede Dormir, Envenenar O\nParalizar Al Contacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(48, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/48.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/48.png', '048', 'Venonat', 'Sus Grandes Ojos Son En Realidad Grupos De Ojos\nDiminutos. Por La Noche Se Siente Atraído Por La Luz.', 10, 300, 'Compound-eyes', 'Aumenta La Precisión Del\nPokémon.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(49, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/49.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/49.png', '049', 'Venomoth', 'Lanza Unas Escamas Que Paralizan A Cualquiera.\nQuien Las Toque, No Podrá Ni Ponerse De Pie.', 15, 125, 'Shield-dust', 'Anula El Efecto Secundario Del\nAtaque Sufrido.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(50, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/50.png', '050', 'Diglett', 'Vive Un Metro Por Debajo Del Suelo, Donde Se Alimenta\nDe Raíces. También Aparece En La Superficie.', 2, 8, 'Sand-veil', 'Aumenta La Evasión En Las\nTormentas De Arena.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(51, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/51.png', '051', 'Dugtrio', 'En Combate, Cava La Tierra, Se Esconde Y Sale De\nRepente Para Golpear A Su Rival. Nunca Se Sabe Por\nDónde Puede Aparecer.', 7, 333, 'Sand-veil', 'Aumenta La Evasión En Las\nTormentas De Arena.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(52, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/52.png', '052', 'Meowth', 'Ein Nachtaktives Pokémon. Sieht Es Etwas\nSchimmerndes, Fangen Seine Augen An Zu Glänzen.', 4, 42, 'Pickup', 'El Pokémon Puede Encontrar\nObjetos.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(53, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/53.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/53.png', '053', 'Persian', 'Aunque Es Muy Admirado Por El Pelo, Es Difícil De\nEntrenar Como Mascota, Porque Es Un Poco Travieso.', 10, 320, 'Limber', 'Evita Ser Paralizado.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(54, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/54.png', '054', 'Psyduck', 'Padece Continuamente Dolores De Cabeza. Cuando\nSon Muy Fuertes, Empieza A Usar Misteriosos Poderes.', 8, 196, 'Damp', 'Evita Que Un Pokémon Pueda\nAutodestruirse.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(55, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/55.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/55.png', '055', 'Golduck', 'Aparece En Ríos Al Anochecer. Puede Usar Poderes\nTelequinéticos Si Su Frente Brilla Misteriosamente.', 17, 766, 'Damp', 'Evita Que Un Pokémon Pueda\nAutodestruirse.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(56, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/56.png', '056', 'Mankey', 'Es Peligroso Acercarse Si Se Enfada Sin Razón Aparente,\nYa Que No Distingue Entre Amigos Y Enemigos.', 5, 280, 'Vital-spirit', 'Evita El Quedarse Dormido.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(57, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/57.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/57.png', '057', 'Primeape', 'Solo Se Calma Cuando Nadie Está Cerca. Llegar A Ver\nEse Momento Es Realmente Difícil.', 10, 320, 'Vital-spirit', 'Evita El Quedarse Dormido.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(58, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/58.png', '058', 'Growlithe', 'Es Muy Agradable Y Leal. Para Ahuyentar Al Enemigo,\nSe Pone A Ladrar Y A Dar Bocados.', 7, 190, 'Intimidate', 'Baja El Ataque Del Rival.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(59, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/59.png', '059', 'Arcanine', 'Un Pokémon Muy Admirado Desde La Antigüedad Por\nSu Belleza. Corre ágilmente Como Si Tuviera Alas.', 19, 1550, 'Intimidate', 'Baja El Ataque Del Rival.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(60, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/60.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/60.png', '060', 'Poliwag', 'Tiene Una Piel Extraordinaria, Fina Y Húmeda, Que Deja\nEntrever Las Vísceras Que Tiene Dispuestas En Espiral.', 6, 124, 'Water-absorb', 'Treffer Durch Wasser-Attacken\nRegenerieren KP.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(61, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/61.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/61.png', '061', 'Poliwhirl', 'Capaz De Vivir Dentro O Fuera Del Agua. Fuera Del Agua\nSuda Para Mantener Baboso Su Cuerpo.', 10, 200, 'Water-absorb', 'Treffer Durch Wasser-Attacken\nRegenerieren KP.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(62, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/62.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/62.png', '062', 'Poliwrath', 'Tiene Músculos Muy Desarrollados. Es Capaz De Nadar\nEn El Océano Sin Descanso.', 13, 540, 'Water-absorb', 'Treffer Durch Wasser-Attacken\nRegenerieren KP.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(63, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/63.png', '063', 'Abra', 'Il Dort 18 H Par Jour. Il Peut Utiliser De Nombreux\nPouvoirs Psy, Même Pendant Son Sommeil.', 9, 195, 'Synchronize', 'Contagia Envenenamiento,\nParálisis O Quemaduras.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(64, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/64.png', '064', 'Kadabra', 'Cuando Utiliza Su Poder Psíquico, Emite Poderosas\nOndas Alfa Que Pueden Destruir Dispositivos.', 13, 565, 'Synchronize', 'Contagia Envenenamiento,\nParálisis O Quemaduras.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(65, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/65.png', '065', 'Alakazam', 'Sus Neuronas Se Multiplican Continuamente Durante Su\nVida. Por Eso, Siempre Lo Recuerda Todo.', 15, 480, 'Synchronize', 'Contagia Envenenamiento,\nParálisis O Quemaduras.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(66, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/66.png', '066', 'Machop', 'Levanta Un Graveler Para Mantener Sus Músculos En\nForma. Domina Todas Las Artes Marciales.', 8, 195, 'Guts', 'Sube El Ataque Si Sufre Un\nProblema De Estado.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(67, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/67.png', '067', 'Machoke', 'Su Musculoso Cuerpo Es Tan Fuerte Que Usa Un Cinto\nAntifuerza Para Controlar Sus Movimientos.', 15, 705, 'Guts', 'Sube El Ataque Si Sufre Un\nProblema De Estado.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(68, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/68.png', '068', 'Machamp', 'Tiene Cuatro Brazos Tan Bien Desarrollados Que Puede\nDar Una Serie De 1000 Puñetazos En Cuestión De Dos\nSegundos.', 16, 1300, 'Guts', 'Sube El Ataque Si Sufre Un\nProblema De Estado.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(69, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/69.png', '069', 'Bellsprout', 'Aunque Su Cuerpo Es Extremadamente Delgado, Es\nMuy Rápido A La Hora De Capturar Sus Presas.', 7, 40, 'Chlorophyll', 'Sube La Velocidad Cuando Hay\nSol.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(70, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/70.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/70.png', '070', 'Weepinbell', 'Ses Membres En Forme De Feuilles Permettent à\nBoustiflor De Trancher Ses Adversaires. Il Crache Un\nFluide Capable De Tout Dissoudre.', 10, 64, 'Chlorophyll', 'Sube La Velocidad Cuando Hay\nSol.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(71, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/71.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/71.png', '071', 'Victreebel', 'Dicen Que Vive En Grandes Colonias En El Interior De\nLas Junglas, Aunque Nadie Ha Podido Verificarlo.', 17, 155, 'Chlorophyll', 'Sube La Velocidad Cuando Hay\nSol.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(72, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/72.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/72.png', '072', 'Tentacool', 'Su Cuerpo Se Compone Casi En Exclusiva De Agua.\nLanza Extraños Rayos Con Sus Ojos Cristalinos.', 9, 455, 'Clear-body', 'Evita Que Bajen Las\nCaracterísticas.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(73, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/73.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/73.png', '073', 'Tentacruel', 'Dieses Pokémon Kann Die Tentakel Bei Der Jagd\nAusfahren, Um Die Beute Leichter Zu Fangen.', 16, 550, 'Clear-body', 'Evita Que Bajen Las\nCaracterísticas.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(74, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/74.png', '074', 'Geodude', 'Aparecen En Llanos Y Montañas. Como Parecen Rocas,\nLa Gente Se Tropieza Con Ellos O Los Pisa.', 4, 200, 'Rock-head', 'Impide Que El Pokémon Se Dañe\nCon Sus Movimientos.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(75, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/75.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/75.png', '075', 'Graveler', 'De Naturaleza Descuidada Y Libre, No Le Importa\nDañarse Cuando Baja Rodando Montañas.', 10, 1050, 'Rock-head', 'Impide Que El Pokémon Se Dañe\nCon Sus Movimientos.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(76, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/76.png', '076', 'Golem', 'Se Lanza Montaña Abajo Y Deja Un Surco Desde La Cima\nHasta El Pie. Es Mejor Mantenerse Alejado.', 14, 3000, 'Rock-head', 'Impide Que El Pokémon Se Dañe\nCon Sus Movimientos.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(77, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/77.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/77.png', '077', 'Ponyta', 'Cuando Nace, Apenas Puede Tenerse En Pie. Pero Va\nFortaleciendo Las Patas En Cuanto Empieza A Galopar.', 10, 300, 'Run-away', 'Permite Escapar De Todos Los\nPokémon Salvajes.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(78, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/78.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/78.png', '078', 'Rapidash', 'Muy Competitivo, Este Pokémon Perseguirá A Todo Lo\nQue Se Mueva Rápido E Intentará Salir Airoso.', 17, 950, 'Run-away', 'Permite Escapar De Todos Los\nPokémon Salvajes.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(79, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/79.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/79.png', '079', 'Slowpoke', 'Está Siempre En Su Mundo, Pero Nadie Sabe En Qué\nPiensa. Suele Pescar Con La Cola.', 12, 360, 'Oblivious', 'Evita Que El Pokémon Sea\nAtraído O Provocado.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(80, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/80.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/80.png', '080', 'Slowbro', 'Tiene Una Cola Tan Apetecible, Que El Shellder Que Va\nEnganchado A Ella No Se Soltará Por Nada Del Mundo.', 16, 785, 'Oblivious', 'Evita Que El Pokémon Sea\nAtraído O Provocado.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(81, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/81.png', '081', 'Magnemite', 'Las Unidades A Los Lados De Su Cuerpo Generan\nEnergía Antigravitatoria Para Mantenerlo En El Aire.', 3, 60, 'Magnet-pull', 'Impide Huir A Los Pokémon De\nTipo Acero.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(82, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/82.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/82.png', '082', 'Magneton', 'Lo Constituye Un Grupo De Magnemite. Descarga\nPotentes Ondas Magnéticas De Alto Voltaje.', 10, 600, 'Magnet-pull', 'Impide Huir A Los Pokémon De\nTipo Acero.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(83, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/83.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/83.png', '083', 'Farfetchd', 'El Puerro Que Lleva Es Su Mejor Arma. Suele Usarlo\nComo Espada Para Cortar Cosas.', 8, 150, 'Keen-eye', 'Evita Que Disminuya La Precisión.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(84, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/84.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/84.png', '084', 'Doduo', 'Este Pokémon De Dos Cabezas Es El Resultado De Una\nMutación. Cuando Corre, Puede Alcanzar Casi 100 Km\nPor Hora.', 14, 392, 'Run-away', 'Permite Escapar De Todos Los\nPokémon Salvajes.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(85, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/85.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/85.png', '085', 'Dodrio', 'Más Vale No Perder De Vista Ninguna De Las Tres\nCabezas. De Lo Contrario, El Número De Picotazos\nSerá Enorme.', 18, 852, 'Run-away', 'Permite Escapar De Todos Los\nPokémon Salvajes.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(86, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/86.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/86.png', '086', 'Seel', 'Este Pokémon Vive En Icebergs. Nada En El Mar Y Usa\nEl Cuerno De Su Cabeza Para Romper El Hielo.', 11, 900, 'Thick-fat', 'Atenúa Los Ataques De Tipo Fuego\nY Hielo.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(87, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/87.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/87.png', '087', 'Dewgong', 'Está Recubierto De Un Luminoso Pelaje Blanco. Este\nPokémon Aumenta Su Actividad Cuando Bajan Las\nTemperaturas.', 17, 1200, 'Thick-fat', 'Atenúa Los Ataques De Tipo Fuego\nY Hielo.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(88, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/88.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/88.png', '088', 'Grimer', 'Nace De Lodo Alterado Al Filtrarse En El Agua Los\nRayos X Reflejados Por La Luna. Se Alimenta De\nSustancias Desagradables.', 9, 300, 'Stench', 'Es Posible Que El Rival Retroceda\nPor El Mal Olor.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(89, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/89.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/89.png', '089', 'Muk', 'Les Encanta Reunirse En Zonas Apestosas Donde Se\nAcumula El Lodo, Haciendo Su Olor Más Insoportable.', 12, 300, 'Stench', 'Es Posible Que El Rival Retroceda\nPor El Mal Olor.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(90, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/90.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/90.png', '090', 'Shellder', 'La Concha Lo Protege De Cualquier Tipo De Ataque.\nSolo Es Vulnerable Cuando Se Abre.', 3, 40, 'Shell-armor', 'Bloquea Los Golpes Críticos.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(91, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/91.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/91.png', '091', 'Cloyster', 'A Los Cloyster Que Viven En Las Fuertes Corrientes\nMarinas Les Crecen Largas Y Afiladas Púas En La Concha.', 15, 1325, 'Shell-armor', 'Bloquea Los Golpes Críticos.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(92, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/92.png', '092', 'Gastly', 'Su Etéreo Cuerpo Está Hecho De Gas. Puede Envolver\nA Un Oponente De Cualquier Tamaño Hasta Ahogarlo.', 13, 1, 'Levitate', 'Proporciona Inmunidad Frente A\nLos Ataques De Tipo Tierra.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(93, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/93.png', '093', 'Haunter', 'Cuando Tienes La Sensación De Que Te Están\nObservando, Seguro Que Es Porque Haunter Está\nCerca.', 16, 1, 'Levitate', 'Proporciona Inmunidad Frente A\nLos Ataques De Tipo Tierra.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(94, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/94.png', '094', 'Gengar', 'Es Versteckt Sich Im Schatten. Man Sagt, Wenn Sich\nEin Gengar Versteckt, Kühlt Es Sich Um 5 °C Ab.', 15, 405, 'Cursed-body', 'Peut Empêcher L’ennemi De\nRéutiliser Une Attaque.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(95, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/95.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/95.png', '095', 'Onix', 'Cava A Gran Velocidad En Busca De Comida. Los\nTúneles Que Deja Son Usados Por Los Diglett.', 88, 2100, 'Rock-head', 'Impide Que El Pokémon Se Dañe\nCon Sus Movimientos.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(96, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/96.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/96.png', '096', 'Drowzee', 'Adormece A Sus Enemigos Y Se Come Sus Sueños.\nA Veces Se Pone Enfermo Si Come Pesadillas.', 10, 324, 'Insomnia', 'Evita El Quedarse Dormido.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(97, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/97.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/97.png', '097', 'Hypno', 'Lleva Un Péndulo En La Mano. Una Vez, Hizo\nDesaparecer A Un Niño Al Que Había Hipnotizado.', 16, 756, 'Insomnia', 'Evita El Quedarse Dormido.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(98, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/98.png', '098', 'Krabby', 'Ante El Peligro, Se Camufla Con Las Burbujas Que\nDesprende Su Boca, Para Parecer Más Grande.', 4, 65, 'Hyper-cutter', 'Evita Que Disminuya El Ataque.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(99, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/99.png', '099', 'Kingler', 'La Pinza Tan Grande Que Tiene Posee Una Fuerza De\n10 000 Caballos De Potencia. Pero, Por Su Gran\nTamaño, Cuesta Moverla.', 13, 600, 'Hyper-cutter', 'Evita Que Disminuya El Ataque.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(100, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/100.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/100.png', '100', 'Voltorb', 'Fue Descubierto Cuando Se Crearon Las Poké Balls.\nSe Dice Que Tiene Algo Que Ver Con Ellas.', 5, 104, 'Soundproof', 'Evita Ataques De Sonido.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(101, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/101.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/101.png', '101', 'Electrode', 'Explotan A La Mínima. Por Eso Se Les Tiene Mucho\nMiedo. Estos Pokémon Reciben El Mote De Bomba Ball.', 12, 666, 'Soundproof', 'Evita Ataques De Sonido.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(102, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/102.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/102.png', '102', 'Exeggcute', 'Estos Seis Huevos Se Comunican Por Telepatía. Si Se\nSeparan, Se Pueden Reunir Rápidamente.', 4, 25, 'Chlorophyll', 'Sube La Velocidad Cuando Hay\nSol.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(103, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/103.png', '103', 'Exeggutor', 'Sus Tres Cabezas Piensan De Forma Independiente.\nSin Embargo, Son Amigas Y No Suelen Discutir Nunca.', 20, 1200, 'Chlorophyll', 'Sube La Velocidad Cuando Hay\nSol.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(104, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/104.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/104.png', '104', 'Cubone', 'Es Trägt Den Schädel Seiner Verstorbenen Mutter Auf\nSeinem Kopf. Fühlt Es Sich Einsam, Soll Es Laut Weinen.', 4, 65, 'Rock-head', 'Impide Que El Pokémon Se Dañe\nCon Sus Movimientos.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(105, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/105.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/105.png', '105', 'Marowak', 'Es Ist Klein Und War Ursprünglich Sehr Schwach.\nErst Als Es Anfing Knochen Einzusetzen, Wurde Es Wild.', 10, 450, 'Rock-head', 'Impide Que El Pokémon Se Dañe\nCon Sus Movimientos.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(106, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/106.png', '106', 'Hitmonlee', 'Encoge Y Estira Las Patas A Su Antojo. Cuando Las\nEstira, Es Capaz De Propinar Una Buena Patada Al\nEnemigo.', 15, 498, 'Limber', 'Evita Ser Paralizado.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(107, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/107.png', '107', 'Hitmonchan', 'Los Potentes Golpes De Sus Brazos Pueden Pulverizar\nEl Hormigón. Descansa Tras Luchar Tres Minutos.', 14, 502, 'Keen-eye', 'Evita Que Disminuya La Precisión.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(108, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/108.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/108.png', '108', 'Lickitung', 'Su Larga Lengua, Recubierta De Saliva Pegajosa, Se\nPega A Todo, Por Lo Que Es Muy útil.', 12, 655, 'Own-tempo', 'Evita Ser Confundido.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(109, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/109.png', '109', 'Koffing', 'Tiene Forma De Globo Y Es Muy Ligero. Está Compuesto\nPor Gases Tóxicos Y Apesta.', 6, 10, 'Levitate', 'Proporciona Inmunidad Frente A\nLos Ataques De Tipo Tierra.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(110, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/110.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/110.png', '110', 'Weezing', 'Si Uno De Los Gemelos Koffing Se Infla, El Otro Se\nDesinfla. Mezclan Constantemente Sus Venenosos\nGases.', 12, 95, 'Levitate', 'Proporciona Inmunidad Frente A\nLos Ataques De Tipo Tierra.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(111, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/111.png', '111', 'Rhyhorn', 'Es Muy Fuerte, Pero No Especialmente Listo. Es Capaz\nDe Derribar Rascacielos Usando Placaje Varias Veces.', 10, 1150, 'Lightning-rod', 'Atrae Y Neutraliza Movimientos De\nTipo Eléctrico Y Sube El At. Esp.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(112, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/112.png', '112', 'Rhydon', 'La Piel Le Sirve De Escudo Protector. Puede Vivir En\nLava Líquida A 2000 °C De Temperatura.', 19, 1200, 'Lightning-rod', 'Atrae Y Neutraliza Movimientos De\nTipo Eléctrico Y Sube El At. Esp.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(113, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/113.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/113.png', '113', 'Chansey', 'Se Dice Que Reparte Felicidad. Se Caracteriza Por Su\nCompasión Y Reparte Sus Huevos Entre La Gente Herida.', 11, 346, 'Natural-cure', 'Cura Problemas De Estado Al\nCambiar De Pokémon.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL);
INSERT INTO `pokemons` (`id`, `image`, `image_shiny`, `code`, `name`, `description`, `height`, `weight`, `ability`, `ability_description`, `created_at`, `updated_at`, `deleted_at`) VALUES
(114, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/114.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/114.png', '114', 'Tangela', 'Se Camufla Con La Multitud De Lianas Que Envuelven Su\nCuerpo Y Que No Dejan De Crecer A Lo Largo De Toda Su\nVida.', 10, 350, 'Chlorophyll', 'Sube La Velocidad Cuando Hay\nSol.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(115, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/115.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/115.png', '115', 'Kangaskhan', 'Lleva A Su Cría En La Bolsa De Su Panza. Solo Deja Que\nSu Cría Salga A Jugar Cuando No Siente Peligro.', 22, 800, 'Early-bird', 'El Pokémon Se Despierta\nRápidamente.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(116, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/116.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/116.png', '116', 'Horsea', 'Dieses Pokémon Schießt Mit Tinte Auf über Der\nWasseroberfläche Fliegende Insekten.', 4, 80, 'Swift-swim', 'Sube La Velocidad Cuando Hay\nLluvia.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(117, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/117.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/117.png', '117', 'Seadra', 'Las Afiladas Púas Que Le Recubren El Cuerpo Se Le\nErizan Y Pueden Causar El Debilitamiento Con Solo\nTocarlo.', 12, 250, 'Poison-point', 'Puede Envenenar Al Mínimo\nContacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(118, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/118.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/118.png', '118', 'Goldeen', 'Es Schwimmt Mit Fünf Knoten. Wird Es Angegriffen,\nWehrt Es Sich Mit Seinem Scharfen Horn.', 6, 150, 'Swift-swim', 'Sube La Velocidad Cuando Hay\nLluvia.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(119, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/119.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/119.png', '119', 'Seaking', 'En Otoño, Cuando Se Reproducen, Se Les Puede Ver\nNadando Con Energía Por Ríos Y Arroyos.', 13, 390, 'Swift-swim', 'Sube La Velocidad Cuando Hay\nLluvia.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(120, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/120.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/120.png', '120', 'Staryu', 'Aunque Sus Brazos Se Rompan Podrán Regenerarse,\nSiempre Y Cuando Su Núcleo Siga Intacto.', 8, 345, 'Illuminate', 'Aumenta La Probabilidad De\nEncontrar Pokémon.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(121, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/121.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/121.png', '121', 'Starmie', 'Su Núcleo Central Brilla Con Los Colores Del Arcoíris.\nPara Algunos Tiene El Valor De Una Gema.', 11, 800, 'Illuminate', 'Aumenta La Probabilidad De\nEncontrar Pokémon.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(122, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/122.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/122.png', '122', 'Mr-mime', 'Para Repeler Ataques, Solidifica El Aire Y Crea Muros\nInvisibles Con Emanaciones De Sus Dedos.', 13, 545, 'Soundproof', 'Evita Ataques De Sonido.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(123, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/123.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/123.png', '123', 'Scyther', 'Destroza A Su Presa Con Las Guadañas Que Tiene.\nNo Es Común Que Use Las Alas Para Volar.', 15, 560, 'Swarm', 'Potencia Los Ataques De Tipo\nBicho En Un Apuro.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(124, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/124.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/124.png', '124', 'Jynx', 'Camina Moviendo Las Caderas De Forma Llamativa.\nPuede Hacer Que La Gente Baile A Su Ritmo.', 14, 406, 'Oblivious', 'Evita Que El Pokémon Sea\nAtraído O Provocado.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(125, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/125.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/125.png', '125', 'Electabuzz', 'Por La Superficie De Su Piel Corre La Electricidad. En La\nOscuridad, Su Cuerpo Se Torna Blanquecino.', 11, 300, 'Static', 'Puede Paralizar Al Mínimo\nContacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(126, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/126.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/126.png', '126', 'Magmar', 'A Este Pokémon Se Lo Encontraron Cerca De Un Volcán.\nEsta Criatura ígnea Tiene Una Temperatura Corporal De\nUnos 1200 °C.', 13, 445, 'Flame-body', 'Puede Quemar Al Mínimo\nContacto.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(127, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/127.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/127.png', '127', 'Pinsir', 'Atrapa Presas Con Sus Pinzas Hasta Que Las Parte En\nDos. Lanza Lejos Lo Que No Puede Quebrar.', 15, 550, 'Hyper-cutter', 'Evita Que Disminuya El Ataque.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(128, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/128.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/128.png', '128', 'Tauros', 'Después De Animarse A Luchar Fustigándose Con Sus\nTres Colas, Carga A Toda Velocidad.', 14, 884, 'Intimidate', 'Baja El Ataque Del Rival.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(129, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/129.png', '129', 'Magikarp', 'No Es Precisamente Rápido Ni Fuerte. Es El Pokémon\nMás Debilucho Y Simplón De Todos Los Que Hay.', 9, 100, 'Swift-swim', 'Sube La Velocidad Cuando Hay\nLluvia.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(130, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/130.png', '130', 'Gyarados', 'En La Literatura Antigua Se Dice Que Un Gyarados\nRebosante De Violencia Arrasó Un Poblado.', 65, 2350, 'Intimidate', 'Baja El Ataque Del Rival.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(131, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/131.png', '131', 'Lapras', 'Son Buenos De Corazón. Muchos Fueron Capturados\nPor Ser Tan Pacíficos. Ahora Hay Muchos Menos.', 25, 2200, 'Water-absorb', 'Treffer Durch Wasser-Attacken\nRegenerieren KP.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(132, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/132.png', '132', 'Ditto', 'Il A La Capacité De Modifier Sa Structure Cellulaire Pour\nPrendre L’apparence De Ce Qu’il Voit.', 3, 40, 'Limber', 'Evita Ser Paralizado.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(133, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/133.png', '133', 'Eevee', 'Un Extraño Pokémon Que Se Adapta A Los Entornos\nMás Hostiles Gracias A Sus Diferentes Evoluciones.', 3, 65, 'Run-away', 'Permite Escapar De Todos Los\nPokémon Salvajes.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(134, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/134.png', '134', 'Vaporeon', 'Es Liebt Schöne Ufer. Da Seine Zellstruktur\nWassermolekülen ähnlich Ist, Kann Es Mit\nWasser Verschmelzen.', 10, 290, 'Water-absorb', 'Treffer Durch Wasser-Attacken\nRegenerieren KP.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(135, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/135.png', '135', 'Jolteon', 'Todos Los Pelos De Su Cuerpo Se Ponen De Punta Si\nEmpieza A Cargarse De Electricidad.', 8, 245, 'Volt-absorb', 'Recupera PS Al Recibir Ataques De\nTipo Eléctrico.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(136, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/136.png', '136', 'Flareon', 'Almacena Llamas En Su Cuerpo, Que Alcanza Una\nTemperatura De 900 °C Antes De Un Combate.', 9, 250, 'Flash-fire', 'Potencia Movimientos De Tipo\nFuego Si Ha Sufrido Antes Alguno.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(137, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/137.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/137.png', '137', 'Porygon', 'Pokémon Creado Por El Hombre Tras Muchas\nInvestigaciones. Sus Habilidades Son Básicas.', 8, 365, 'Trace', 'Copia La Habilidad Del Rival.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(138, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/138.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/138.png', '138', 'Omanyte', 'Pokémon Prehistórico Que Vivió En El Océano\nPrimordial. Para Nadar Se Valía De Sus 10 Tentáculos.', 4, 75, 'Swift-swim', 'Sube La Velocidad Cuando Hay\nLluvia.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(139, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/139.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/139.png', '139', 'Omastar', 'Tiene Los Tentáculos Tan Desarrollados Que Le Sirven De\nManos Y Pies. Con Ellos Atrapa A Su Presa Y Le Da Un\nBocado.', 10, 350, 'Swift-swim', 'Sube La Velocidad Cuando Hay\nLluvia.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(140, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/140.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/140.png', '140', 'Kabuto', 'Se Cree Que Habitó Las Playas Hace 300 Millones De\nAños. Se Protege Con Una Dura Concha.', 5, 115, 'Swift-swim', 'Sube La Velocidad Cuando Hay\nLluvia.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(141, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/141.png', '141', 'Kabutops', 'Repliega Sus Extremidades En El Agua Para Hacerse\nMás Compacto, Y Mueve Su Concha Para Nadar Rápido.', 13, 405, 'Swift-swim', 'Sube La Velocidad Cuando Hay\nLluvia.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(142, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/142.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/142.png', '142', 'Aerodactyl', 'Se Regeneró A Partir De Material Genético De Un\nDinosaurio Encontrado En ámbar. Cuando Vuela Emite\nEscandalosos Alaridos.', 18, 590, 'Rock-head', 'Impide Que El Pokémon Se Dañe\nCon Sus Movimientos.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(143, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/143.png', '143', 'Snorlax', 'No Se Encuentra Satisfecho Hasta Que No Se Come\n400 Kg De Comida Cada Día. Cuando Acaba De Comer,\nSe Queda Dormido.', 21, 4600, 'Immunity', 'Evita El Envenenamiento.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(144, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/144.png', '144', 'Articuno', 'Legendario Pokémon Pájaro Capaz De Generar\nVentiscas Congelando La Humedad Del Aire.', 17, 554, 'Pressure', 'Hace Que Los PP Del Rival Se\nAcaben Antes.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(145, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/145.png', '145', 'Zapdos', 'Es Un Legendario Pájaro Pokémon. Dicen Que Aparece\nEntre Las Nubes Lanzando Enormes Rayos Brillantes.', 16, 526, 'Pressure', 'Hace Que Los PP Del Rival Se\nAcaben Antes.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(146, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/146.png', '146', 'Moltres', 'Dieses Pokémon Ist Der Legendäre Feuervogel.\nSein Flügelschlag Entfacht Ein Helles Feuermeer.', 20, 600, 'Pressure', 'Hace Que Los PP Del Rival Se\nAcaben Antes.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(147, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/147.png', '147', 'Dratini', 'Se Le Llama El Pokémon Espejismo Porque Son Muy\nPocos Los Que Lo Han Visto. Se Encontró Su Muda.', 18, 33, 'Shed-skin', 'Cura Los Problemas De Estado\nMudando La Piel.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(148, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/148.png', '148', 'Dragonair', 'Sus Cristalinos Orbes Parecen Darle Al Pokémon El\nPoder De Controlar El Clima Libremente.', 40, 165, 'Shed-skin', 'Cura Los Problemas De Estado\nMudando La Piel.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(149, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/149.png', '149', 'Dragonite', 'A Pesar Del Tamaño Que Tiene Y De Lo Pesado Que Es,\nPuede Volar. Es Capaz De Dar La Vuelta Al Mundo En\nSolo 16 Horas.', 22, 2100, 'Inner-focus', 'Evita El Retroceso.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(150, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/150.png', '150', 'Mewtwo', 'Fue Creado Por Un Científico Tras Años De Horribles\nExperimentos De Ingeniería Genética.', 20, 1220, 'Pressure', 'Hace Que Los PP Del Rival Se\nAcaben Antes.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL),
(151, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/151.png', '151', 'Mew', 'Varios Científicos Lo Consideran El Antecesor De Los\nPokémon Porque Usa Todo Tipo De Movimientos.', 4, 40, 'Synchronize', 'Contagia Envenenamiento,\nParálisis O Quemaduras.', '2021-03-09 16:56:53', '2021-03-09 16:56:53', NULL);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `pokemons`
--
ALTER TABLE `pokemons`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `pokemons`
--
ALTER TABLE `pokemons`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=152;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
